package com.klifora.shop.models.searchOrder

data class Item(
//    val additional_data: Any,
    val amount_refunded: String,
//    val applied_rule_ids: Any,
    val base_amount_refunded: String,
//    val base_cost: Any,
    val base_discount_amount: String,
    val base_discount_invoiced: String,
//    val base_discount_refunded: Any,
    val base_discount_tax_compensation_amount: String,
    val base_discount_tax_compensation_invoiced: String,
//    val base_discount_tax_compensation_refunded: Any,
    val base_original_price: String,
    val base_price: String,
    val base_price_incl_tax: String,
    val base_row_invoiced: String,
    val base_row_total: String,
    val base_row_total_incl_tax: String,
    val base_tax_amount: String,
//    val base_tax_before_discount: Any,
    val base_tax_invoiced: String,
//    val base_tax_refunded: Any,
//    val base_weee_tax_applied_amount: Any,
//    val base_weee_tax_applied_row_amnt: Any,
//    val base_weee_tax_disposition: Any,
//    val base_weee_tax_row_disposition: Any,
    val created_at: String,
//    val description: Any,
    val discount_amount: String,
    val discount_invoiced: String,
    val discount_percent: String,
//    val discount_refunded: Any,
    val discount_tax_compensation_amount: String,
//    val discount_tax_compensation_canceled: Any,
    val discount_tax_compensation_invoiced: String,
//    val discount_tax_compensation_refunded: Any,
//    val ext_order_item_id: Any,
    val free_shipping: String,
    val gift_message_available: String,
//    val gift_message_id: Any,
    val is_qty_decimal: String,
    val is_virtual: String,
    val item_id: String,
//    val locked_do_invoice: Any,
//    val locked_do_ship: Any,
    val name: String,
    val no_discount: String,
    val order_id: String,
    val original_price: String,
//    val parent_item_id: Any,
    val price: String,
    val price_incl_tax: String,
    val product_id: String,
    val product_options: ProductOptions,
    val product_type: String,
//    val qty_backordered: Any,
    val qty_canceled: String,
    val qty_invoiced: String,
    val qty_ordered: String,
    val qty_refunded: String,
    val qty_shipped: String,
    val quote_item_id: String,
    val row_invoiced: String,
    val row_total: String,
    val row_total_incl_tax: String,
    val row_weight: String,
    val sku: String,
    val store_id: String,
    val tax_amount: String,
//    val tax_before_discount: Any,
//    val tax_canceled: Any,
    val tax_invoiced: String,
    val tax_percent: String,
//    val tax_refunded: Any,
    val updated_at: String,
    val weee_tax_applied: String,
//    val weee_tax_applied_amount: Any,
//    val weee_tax_applied_row_amount: Any,
//    val weee_tax_disposition: Any,
//    val weee_tax_row_disposition: Any,
    val weight: String
)